"""
SQLAlchemy Core table definitions — the single source of truth for the
database schema. Alembic migrations target this metadata, and tests create
their schema from it via metadata.create_all().

Storage conventions:
  - IDs are UUIDv4 strings (TEXT), generated by utils.new_id().
  - Timestamps/dates are TEXT ISO-8601, exactly as Pydantic's
    model_dump(mode="json") produces; Pydantic parses them back on load.
  - Booleans are INTEGER 0/1.
  - Session status is never stored — computed by utils.compute_session_status().
  - orders.pizza_id has no FK on purpose: pizza name/price are order-time
    snapshots and must survive later menu edits/deletions.
"""
from sqlalchemy import (
    CheckConstraint,
    Column,
    Float,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    Table,
    Text,
    text,
)

metadata = MetaData()

admins = Table(
    "admins",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("username", Text, nullable=False, unique=True),
    Column("password_hash", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Column("token_version", Integer, nullable=False, server_default="0"),
    # UI language tag ("en", "de-CH", "fr-CH", "it-CH"); NULL = no explicit
    # choice, follow the browser. A per-login preference, not a team setting.
    Column("language", Text, nullable=True),
)

teams = Table(
    "teams",
    metadata,
    Column("id", Text, primary_key=True),
    Column("team_name", Text, nullable=False),
    Column("unique_link", Text, nullable=False, unique=True),
    Column("currency", Text, nullable=False, server_default="CHF"),
    # "name" | "email" — what the public ordering form asks team members for.
    Column("member_identifier", Text, nullable=False, server_default="name"),
    # Set by the "reset counters" action on the stats page; NULL = no cutoff,
    # count the team's entire history. Never clears rows — only shifts which
    # sessions the stats aggregations consider.
    Column("stats_reset_at", Text, nullable=True),
    # Preselects the grace period stepper on the "new session" form so the CPO
    # doesn't have to re-tune it every time; still editable per session.
    Column("default_grace_period_minutes", Integer, nullable=False, server_default="2"),
    Column("created_at", Text, nullable=False),
)

cpos = Table(
    "cpos",
    metadata,
    Column("id", Text, primary_key=True),
    Column("team_id", Text, ForeignKey("teams.id", ondelete="CASCADE"), nullable=False),
    Column("username", Text, nullable=False, unique=True),
    Column("email", Text, nullable=False, unique=True),
    Column("password_hash", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Column("token_version", Integer, nullable=False, server_default="0"),
    # See admins.language — same per-login meaning.
    Column("language", Text, nullable=True),
)

team_invites = Table(
    "team_invites",
    metadata,
    Column("id", Text, primary_key=True),
    Column("team_id", Text, ForeignKey("teams.id", ondelete="CASCADE"), nullable=False),
    Column("token", Text, nullable=False, unique=True),
    Column("created_by_cpo_id", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Column("expires_at", Text, nullable=False),
    # Set once the invite is redeemed; single-use — a non-null value blocks reuse.
    Column("used_at", Text, nullable=True),
    Index("ix_team_invites_team", "team_id"),
)

menus = Table(
    "menus",
    metadata,
    Column("id", Text, primary_key=True),
    Column("team_id", Text, ForeignKey("teams.id", ondelete="CASCADE"), nullable=False),
    Column("name", Text, nullable=False, server_default="Default"),
    Column("is_default", Integer, nullable=False, server_default="1"),
    Column("pizzeria_url", Text, nullable=True),
    Index(
        "ux_menus_one_default",
        "team_id",
        unique=True,
        sqlite_where=text("is_default = 1"),
    ),
)

pizzas = Table(
    "pizzas",
    metadata,
    Column("id", Text, primary_key=True),
    Column("menu_id", Text, ForeignKey("menus.id", ondelete="CASCADE"), nullable=False),
    Column("name", Text, nullable=False),
    Column("price", Float, nullable=False),
    CheckConstraint("price >= 0.01", name="ck_pizzas_price_min"),
    Index("ix_pizzas_menu", "menu_id"),
)

sessions = Table(
    "sessions",
    metadata,
    Column("id", Text, primary_key=True),
    Column("team_id", Text, ForeignKey("teams.id", ondelete="CASCADE"), nullable=False),
    Column("team_name", Text, nullable=False),
    Column("session_date", Text, nullable=False),
    Column("start_time", Text, nullable=False),
    Column("end_time", Text, nullable=False),
    Column("grace_period_minutes", Integer, nullable=False, server_default="2"),
    Column("created_at", Text, nullable=False),
    Column("closed_at", Text, nullable=True),
    # SET NULL so closed-session history never pins a menu; active/upcoming
    # sessions are protected by a service-level check instead (status is
    # computed from times, never stored, so it cannot be a constraint).
    Column("menu_id", Text, ForeignKey("menus.id", ondelete="SET NULL"), nullable=True),
    CheckConstraint("grace_period_minutes >= 0", name="ck_sessions_grace_min"),
    Index("ix_sessions_team_created", "team_id", "created_at"),
)

orders = Table(
    "orders",
    metadata,
    Column("id", Text, primary_key=True),
    Column("session_id", Text, ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False),
    Column("member_name", Text, nullable=False),
    Column("pizza_id", Text, nullable=False),
    Column("pizza_name", Text, nullable=False),
    Column("pizza_price", Float, nullable=False),
    Column("quantity", Integer, nullable=False, server_default="1"),
    Column("total_price", Float, nullable=False),
    Column("created_at", Text, nullable=False),
    Column("client_ip", Text, nullable=False),
    Column("comment", Text, nullable=True),
    Column("received", Integer, nullable=False, server_default="0"),
    CheckConstraint("quantity >= 1", name="ck_orders_quantity_min"),
    Index("ix_orders_session", "session_id"),
)
